/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory */

#ifndef _Included_net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
#define _Included_net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
 * Method:    allocateRemoteData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_bytebuddy_agent_VirtualMachine_00024ForHotSpot_00024Connection_00024ForJnaWindowsNamedPipe_00024Factory_allocateRemoteData
  (JNIEnv *, jclass, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
 * Method:    getRemoteDataSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bytebuddy_agent_VirtualMachine_00024ForHotSpot_00024Connection_00024ForJnaWindowsNamedPipe_00024Factory_getRemoteDataSize
  (JNIEnv *, jclass);

/*
 * Class:     net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
 * Method:    getRemoteEntryPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bytebuddy_agent_VirtualMachine_00024ForHotSpot_00024Connection_00024ForJnaWindowsNamedPipe_00024Factory_getRemoteEntryPointer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
