/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory */

#ifndef _Included_net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
#define _Included_net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
 * Method:    allocateRemoteCode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_bytebuddy_agent_VirtualMachine_00024ForHotSpot_00024Connection_00024ForJnaWindowsNamedPipe_00024Factory_allocateRemoteCode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_bytebuddy_agent_VirtualMachine_ForHotSpot_Connection_ForJnaWindowsNamedPipe_Factory
 * Method:    getRemoteDataSize
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_bytebuddy_agent_VirtualMachine_00024ForHotSpot_00024Connection_00024ForJnaWindowsNamedPipe_00024Factory_allocateRemoteArgument
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
