name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # You can change this to the Java version you need

      - name: Build with Maven
        run: mvn clean install -DskipTests -pl byte-buddy-dep -am

      - name: Run NonDex
        run: |
          mvn -pl byte-buddy-dep test -Dtest=net.bytebuddy.description.method.MethodDescriptionForLoadedTest#testExceptions
          mvn -pl byte-buddy-dep edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=net.bytebuddy.description.method.MethodDescriptionForLoadedTest#testExceptions
