name: Scorecards
on:
  branch_protection_rule:
  schedule:
    - cron: '36 17 * * 5'
  push:
    branches: [ "master" ]
permissions: read-all
jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@aa578102511db1f4524ed59b8cc2bae4f6e88195 # v3.27.6
        with:
          sarif_file: results.sarif
